config/routes.rb
Rails.application.routes.draw do
  match '/experimental/compliance' => 'react#index', :via => [:get]
  match '/experimental/compliance/*page' => 'react#index', :via => [:get]

  scope '/compliance' do
    resources :arf_reports, :only => %i[index show destroy] do
      member do
        get 'show_html'
        get 'parse_html'
        get 'parse_bzip'
        get 'download_html'
        get 'show_log'
      end
      collection do
        get 'auto_complete_search'
        get 'delete_multiple'
        post 'submit_delete_multiple'
      end
    end

    get 'dashboard', :to => 'compliance_dashboard#index', :as => "compliance_dashboard"

    resources :policies, :only => %i[index new show create edit update destroy] do
      member do
        get 'parse', :to => 'policies#parse'
        get 'dashboard', :to => 'policy_dashboard#index', :as => 'policy_dashboard'
      end
      collection do
        get 'auto_complete_search'
        post 'scap_content_selected'
        post 'tailoring_file_selected'
        post 'select_multiple_hosts'
        post 'update_multiple_hosts'
        post 'disassociate_multiple_hosts'
        post 'remove_policy_from_multiple_hosts'
      end
    end

    resources :scap_contents do
      collection do
        get 'auto_complete_search'
      end
    end

    resources :tailoring_files, :except => [:show] do
      member do
        get 'xml'
      end
      collection do
        get 'auto_complete_search'
      end
    end

    resources :openscap_proxies, :only => [] do
      member do
        get 'openscap_spool'
      end
    end

    resources :hosts, :only => [:show], :as => :compliance_hosts, :controller => :compliance_hosts
  end

  namespace :api, :defaults => { :format => 'json' } do
    scope "(:apiv)", :module => :v2, :defaults => { :apiv => 'v2' },
                     :apiv => /v2/, :constraints => ApiConstraints.new(:version => 2, :default => true) do
      namespace :compliance do
        resources :scap_contents, :except => %i[new edit] do
          member do
            get 'xml'
          end
          collection do
            post 'bulk_upload'
          end
        end
        resources :scap_content_profiles, :only => %i[index]

        resources :tailoring_files, :except => %i[new edit] do
          member do
            get 'xml'
          end
        end
        resources :policies, :except => %i[new edit] do
          member do
            get 'content'
            get 'tailoring'
          end
        end
        resources :arf_reports, :only => %i[index show destroy] do
          member do
            get 'download'
            get 'download_html'
          end
        end

        post 'arf_reports/:cname/:policy_id/:date', \
             :constraints => { :cname => /[^\/]+/ }, :to => 'arf_reports#create'
      end

      constraints(:id => /[^\/]+/) do
        resources :hosts, :only => [] do
          member do
            get :policies_enc
          end
        end
      end
    end
  end
end

Foreman::Application.routes.draw do
  resources :hosts do
    collection do
      post 'openscap_proxy_changed'
      post 'select_multiple_openscap_proxy'
      post 'update_multiple_openscap_proxy'
    end
  end

  resources :hostgroups do
    collection do
      post 'openscap_proxy_changed'
    end
  end
end

app/helpers/dashboard_helper.rb
#
# Copyright (c) 2014 Red Hat Inc.
#
# This software is licensed to you under the GNU General Public License,
# version 3 (GPLv3). There is NO WARRANTY for this software, express or
# implied, including the implied warranties of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. You should have received a copy of GPLv3
# along with this software; if not, see http://www.gnu.org/licenses/gpl.txt
#

module DashboardHelper

  def latest_headers
    string =  "<th>#{_("Host")}</th>"
    string += "<th>#{_("Policy")}</th>"
    # TRANSLATORS: initial character of Passed
    string += translated_header(s_('Passed|P'), _('Passed'))
    # TRANSLATORS: initial character of Failed
    string += translated_header(s_('Failed|F'), _('Failed'))
    # TRANSLATORS: initial character of Othered which is an SCAP term
    string += translated_header(s_('Othered|O'), _('Othered'))

    string.html_safe
  end

end

app/views/dashboard/_compliance_host_reports_widget.html.erb
<h4 class="ca"><%= _('Latest Compliance Reports') %></h4>
<% latest_reports = ForemanOpenscap::ArfReport.latest.limit(9) %>
<% if latest_reports.empty? %>
  <p class="ca"><%= _("No reports available") %></p>
<% else %>
  <table class="<%= table_css_classes('table-fixed') %>">
    <tr>
      <%= latest_compliance_headers %>
    </tr>
    <% latest_reports.each do |report| %>
      <tr>
        <td class="ellipsis"><%= link_to h(report.host.nil? ? _('Host does not exist anymore') : report.host.name), arf_report_path(report) %></td>
        <td class="ellipsis"><%= report.policy.nil? ? _('Policy is missing') :  link_to(h(report.policy.name), policy_dashboard_policy_path(report.policy)) %></td>
        <td class="ca"><%= report_event_column(report.passed, "label-success")  %></td>
        <td class="ca"><%= report_event_column(report.failed, "label-danger")  %></td>
        <td class="ca"><%= report_event_column(report.othered, "label-info")  %></td>
      </tr>
    <% end %>
  </table>
<% end %>

app/views/dashboard/_compliance_reports_breakdown_widget.html.erb
<h4 class="header ca"><%= _('Compliance Reports Breakdown') %></h4>
<div class="host-configuration-chart">
  <% report = ForemanOpenscap::ReportDashboard::Data.new().report %>
  <%= react_component('DonutChart', :data => donut_breakdown_chart_data(report)) %>
</div>