config/routes.rb
Rails.application.routes.draw do
  match '/experimental/compliance' => 'react#index', :via => [:get]
  match '/experimental/compliance/*page' => 'react#index', :via => [:get]

  scope '/compliance' do
    resources :arf_reports, :only => %i[index show destroy] do
      member do
        get 'show_html'
        get 'parse_html'
        get 'parse_bzip'
        get 'download_html'
        get 'show_log'
      end
      collection do
        get 'auto_complete_search'
        get 'delete_multiple'
        post 'submit_delete_multiple'
      end
    end

    get 'dashboard', :to => 'compliance_dashboard#index', :as => "compliance_dashboard"

    resources :policies, :only => %i[index new show create edit update destroy] do
      member do
        get 'parse', :to => 'policies#parse'
        get 'dashboard', :to => 'policy_dashboard#index', :as => 'policy_dashboard'
      end
      collection do
        get 'auto_complete_search'
        post 'scap_content_selected'
        post 'tailoring_file_selected'
        post 'select_multiple_hosts'
        post 'update_multiple_hosts'
        post 'disassociate_multiple_hosts'
        post 'remove_policy_from_multiple_hosts'
      end
    end

    resources :scap_contents do
      collection do
        get 'auto_complete_search'
      end
    end

    resources :tailoring_files, :except => [:show] do
      member do
        get 'xml'
      end
      collection do
        get 'auto_complete_search'
      end
    end

    resources :openscap_proxies, :only => [] do
      member do
        get 'openscap_spool'
      end
    end

    resources :hosts, :only => [:show], :as => :compliance_hosts, :controller => :compliance_hosts
  end

  namespace :api, :defaults => { :format => 'json' } do
    scope "(:apiv)", :module => :v2, :defaults => { :apiv => 'v2' },
                     :apiv => /v2/, :constraints => ApiConstraints.new(:version => 2, :default => true) do
      namespace :compliance do
        resources :scap_contents, :except => %i[new edit] do
          member do
            get 'xml'
          end
          collection do
            post 'bulk_upload'
          end
        end
        resources :scap_content_profiles, :only => %i[index]

        resources :tailoring_files, :except => %i[new edit] do
          member do
            get 'xml'
          end
        end
        resources :policies, :except => %i[new edit] do
          member do
            get 'content'
            get 'tailoring'
          end
        end
        resources :arf_reports, :only => %i[index show destroy] do
          member do
            get 'download'
            get 'download_html'
          end
        end

        post 'arf_reports/:cname/:policy_id/:date', \
             :constraints => { :cname => /[^\/]+/ }, :to => 'arf_reports#create'
      end

      constraints(:id => /[^\/]+/) do
        resources :hosts, :only => [] do
          member do
            get :policies_enc
          end
        end
      end
    end
  end
end

Foreman::Application.routes.draw do
  resources :hosts do
    collection do
      post 'openscap_proxy_changed'
      post 'select_multiple_openscap_proxy'
      post 'update_multiple_openscap_proxy'
    end
  end

  resources :hostgroups do
    collection do
      post 'openscap_proxy_changed'
    end
  end
end

app/models/foreman_openscap/scap_content.rb
module ForemanOpenscap
  class ScapContent < ApplicationRecord
    audited :except => [:scap_file]
    include Authorizable
    include Taxonomix
    include DataStreamContent
    include ScapFileContent

    has_many :scap_content_profiles, :dependent => :destroy
    has_many :policies

    validates :title, :presence => true, :length => { :maximum => 255 }, uniqueness: true
    validates :original_filename, :length => { :maximum => 255 }

    scoped_search :on => :title,             :complete_value => true
    scoped_search :on => :original_filename, :complete_value => true, :rename => :filename
    scoped_search :on => :created_at

    default_scope do
      with_taxonomy_scope do
        order("foreman_openscap_scap_contents.title")
      end
    end

    def used_location_ids
      Location.joins(:taxable_taxonomies).where(
        'taxable_taxonomies.taxable_type' => 'ForemanOpenscap::ScapContent',
        'taxable_taxonomies.taxable_id' => id
      ).pluck("#{Location.arel_table.name}.id")
    end

    def used_organization_ids
      Organization.joins(:taxable_taxonomies).where(
        'taxable_taxonomies.taxable_type' => 'ForemanOpenscap::ScapContent',
        'taxable_taxonomies.taxable_id' => id
      ).pluck("#{Location.arel_table.name}.id")
    end

    def to_label
      title
    end

    def as_json(*args)
      hash = super
      hash["scap_file"] = scap_file.to_s.encode('utf-8', :invalid => :replace, :undef => :replace, :replace => '_')
    end

    def fetch_profiles
      api = ProxyAPI::Openscap.new(:url => proxy_url)
      profiles = api.fetch_policies_for_scap_content(scap_file)
      profiles
    end
  end
end

app/controllers/api/v2/compliance/scap_contents_controller.rb
module Api::V2
  module Compliance
    class ScapContentsController < ::Api::V2::BaseController
      include Foreman::Controller::Parameters::ScapContent
      include ForemanOpenscap::BodyLogExtensions
      include ForemanOpenscap::Api::V2::ScapApiControllerExtensions

      def self.bulk_upload_types
        ['files', 'directory', 'default']
      end

      before_action :find_resource, :except => %w[index create bulk_upload]

      api :GET, '/compliance/scap_contents', N_('List SCAP contents')
      param_group :search_and_pagination, ::Api::V2::BaseController
      add_scoped_search_description_for(::ForemanOpenscap::ScapContent)

      def index
        @scap_contents = resource_scope_for_index(:permission => :view_scap_contents)
      end

      api :GET, '/compliance/scap_contents/:id/xml', N_('Download an SCAP content as XML')
      param :id, :identifier, :required => true

      def xml
        send_data @scap_content.scap_file,
                  :type     => 'application/xml',
                  :filename => @scap_content.original_filename || "#{@scap_content.title}.xml"
      end

      api :GET, '/compliance/scap_contents/:id', N_('Show an SCAP content')
      param :id, :identifier, :required => true
      def show
      end

      def_param_group :scap_content do
        param :scap_content, Hash, :required => true, :action_aware => true do
          param :title, String, :required => true, :desc => N_('SCAP content name')
          param :scap_file, String, :required => true, :desc => N_('XML containing SCAP content')
          param :original_filename, String, :desc => N_('Original file name of the XML file')
          param_group :taxonomies, ::Api::V2::BaseController
        end
      end

      api :POST, '/compliance/scap_contents', N_('Create SCAP content')
      param_group :scap_content, :as => :create

      def create
        @scap_content = ForemanOpenscap::ScapContent.new(scap_content_params)
        process_response @scap_content.save
      end

      api :PUT, '/compliance/scap_contents/:id', N_('Update an SCAP content')
      param :id, :identifier, :required => true
      param_group :scap_content

      def update
        process_response @scap_content.update(scap_content_params)
      end

      api :DELETE, '/compliance/scap_contents/:id', N_('Deletes an SCAP content')
      param :id, :identifier, :required => true

      def destroy
        process_response @scap_content.destroy
      end

      api :POST, '/compliance/scap_contents/bulk_upload', N_('Upload scap contents in bulk')
      param :type, bulk_upload_types, :required => true, :desc => N_('Type of the upload')
      param :files, Array, :desc => N_('File paths to upload when using "files" upload type')
      param :directory, String, :desc => N_('Directory to upload when using "directory" upload type')

      def bulk_upload
        case params[:type]
        when 'files'
          @result = ForemanOpenscap::BulkUpload.new.upload_from_files(params[:files])
        when 'directory'
          @result = ForemanOpenscap::BulkUpload.new.upload_from_directory(params[:directory])
        when 'default'
          @result = ForemanOpenscap::BulkUpload.new.upload_from_scap_guide
        else
          return render :json => {
            :errors => [
              _("Please specify import type, received: %{received}, expected one of: %{expected}") %
                { :expected => self.class.bulk_upload_types.join(', '), :received => params[:type] }
            ]
          }, :status => :unprocessable_entity
        end
      end

      private

      def find_resource
        not_found && return if params[:id].blank?
        instance_variable_set("@scap_content", resource_scope.find(params[:id]))
      end

      def action_permission
        case params[:action]
        when 'bulk_upload'
          :create
        when 'xml'
          :view
        else
          super
        end
      end
    end
  end
end

app/controllers/api/v2/scap_contents_controller.rb
module Api
  module V2
    class ScapContentsController < ::Api::V2::BaseController
      before_filter :find_resource, :except => %w{index create}

      def resource_name
        'Scaptimony::ScapContent'
      end

      def get_resource
        instance_variable_get :"@scap_content" or raise 'no resource loaded'
      end

      resource_description do
        resource_id 'scaptimony_scap_contents'
        api_version 'v2'
        api_base_url "/api/v2"
      end

      api :GET, '/scap_contents', N_('List SCAP contents')
      param_group :search_and_pagination, ::Api::V2::BaseController

      def index
        @scap_contents = resource_scope_for_index(:permission => :edit_compliance)
      end

      api :GET, '/scap_contents/:id', N_('Show an SCAP content')
      param :id, :identifier, :required => true

      def show
        send_data @scap_content.scap_file,
                  :type     => 'application/xml',
                  :filename => @scap_content.original_filename
      end

      def_param_group :scap_content do
        param :scap_content, Hash, :required => true, :action_aware => true do
          param :title, String, :required => true, :desc => N_('Scap content name')
          param :scap_file, String, :required => true
          param_group :taxonomies, ::Api::V2::BaseController
        end
      end

      api :POST, 'scap_contents', N_('Create SCAP content')
      param_group :scap_content, :as => :create

      def create
        @scap_content = Scaptimony::ScapContent.new(params[:scap_content])
        process_response @scap_content.save
      end

      api :PUT, '/scap_contents/:id', N_('Update an SCAP content')
      param :id, :identifier, :required => true
      param_group :scap_content

      def update
        process_response @scap_content.update_attributes(params[:scap_content])
      end

      api :DELETE, '/scap_contents/:id', N_('Deletes an SCAP content')
      param :id, :identifier, :required => true

      def destroy
        process_response @scap_content.destroy
      end

      private
      def find_resource
        not_found and return if params[:id].blank?
        instance_variable_set("@scap_content", resource_scope.find(params[:id]))
      end
    end
  end
end

app/controllers/concerns/foreman/controller/parameters/scap_content.rb
module Foreman::Controller::Parameters::ScapContent
  extend ActiveSupport::Concern

  class_methods do
    def scap_content_params_filter
      Foreman::ParameterFilter.new(::ForemanOpenscap::ScapContent).tap do |filter|
        filter.permit :original_filename, :scap_file, :title, :location_ids => [], :organization_ids => []
      end
    end
  end

  def scap_content_params
    self.class.scap_content_params_filter.filter_params(params, parameter_filter_context)
  end
end

app/controllers/scap_contents_controller.rb
class ScapContentsController < ApplicationController
  include Foreman::Controller::AutoCompleteSearch
  include Foreman::Controller::Parameters::ScapContent

  before_action :handle_file_upload, :only => %i[create update]
  before_action :find_by_id, :only => %i[show edit update destroy]

  def model_of_controller
    ::ForemanOpenscap::ScapContent
  end

  def index
    @contents = resource_base_search_and_page.search_for(params[:search])
  end

  def show
    send_data @scap_content.scap_file,
              :type     => 'application/xml',
              :filename => @scap_content.original_filename
  end

  def new
    @scap_content = ForemanOpenscap::ScapContent.new
  end

  def create
    @scap_content = ForemanOpenscap::ScapContent.new(scap_content_params)
    if @scap_content.save
      process_success
    else
      process_error
    end
  end

  def update
    if @scap_content.update(scap_content_params)
      process_success
    else
      process_error
    end
  end

  def destroy
    if @scap_content.destroy
      process_success
    else
      process_error :object => @scap_content
    end
  end

  private

  def find_by_id
    @scap_content = resource_base.find(params[:id])
  end

  def handle_file_upload
    return unless params[:scap_content] && scap_raw_file = params[:scap_content][:scap_file]
    params[:scap_content][:original_filename] = scap_raw_file.original_filename
    params[:scap_content][:scap_file] = scap_raw_file.tempfile.read if scap_raw_file.tempfile.respond_to?(:read)
  end
end

app/views/scap_contents/_form.html.erb
<%= form_for @scap_content,
    :url => (@scap_content.id? ?
        scap_content_path(:id => @scap_content.id) : scap_contents_path),
    :html => { :multipart => true } do |f| %>

  <%= base_errors_for @scap_content %>

  <ul class="nav nav-tabs" data-tabs="tabs">
    <li class="active"><a href="#primary" data-toggle="tab"><%= _("File Upload") %></a></li>
    <% if show_location_tab? %>
      <li><a href='#locations' data-toggle='tab'><%= _('Locations') %></a></li>
    <% end %>
    <% if show_organization_tab? %>
      <li><a href='#organizations' data-toggle='tab'><%= _('Organizations') %></a></li>
    <% end %>
  </ul>
  <div class="tab-content">
    <div class="tab-pane active" id="primary">
      <%= text_f(f, :title) %>
      <%= file_field_f f, :scap_file, :file_name => @scap_content.original_filename , :label_help  => _("SCAP DataStream file") %>
    </div>
    <%= render 'taxonomies/loc_org_tabs', :f => f, :obj => @scap_content %>
    <%= submit_or_cancel f %>
  </div>
<% end %>

app/views/scap_contents/_list.html.erb
<table class="<%= table_css_classes('table-two-pane table-fixed') %>">
  <tr>
    <th class="col-md-4"><%= sort :title, as: _('Title') %></th>
    <th class="col-md-5"><%= sort :filename, as: _('File name') %></th>
    <th class="col-md-2"><%= sort :created_at, as: _('Created at') %></th>
    <th class="col-md-1"><%= _('Actions') %></th>
  </tr>
  <% for content in @contents %>
    <tr>
      <td class="ellipsis"><%= link_to_if_authorized content.title, hash_for_edit_scap_content_path(:id => content.id) %></td>
      <td class="ellipsis"><%= content.original_filename %></td>
      <td>
        <%= date_time_relative_value(content.created_at.getlocal) %>
      </td>
      <td>
        <%= action_buttons(
		display_link_if_authorized(_("Download"), hash_for_scap_content_path(:id => content.id), :data => { :no_turbolink => true }),
                display_delete_if_authorized(hash_for_scap_content_path(:id => content.id),
                                             :data => {:confirm => _("Delete scap content %s?") % content.title})
            ) %>
      </td>
    </tr>
  <% end %>
</table>

<%= will_paginate_with_info @contents %>

app/views/scap_contents/edit.html.erb
<% title _("Edit %s") % @scap_content.title %>
<%= breadcrumbs(:resource_url => api_compliance_scap_contents_path,
                :name_field => 'title') %>

<%= render :partial => 'form' %>

app/views/scap_contents/index.html.erb
<% title _("SCAP Contents") %>

<% title_actions(display_link_if_authorized(_("Upload New SCAP Content"), hash_for_new_scap_content_path, :class => 'btn btn-primary'),
                 scap_doc_button('Configuring_SCAP_Contents_security-compliance')) %>

<%= render :partial => 'list' %>

app/views/scap_contents/new.html.erb
<% title _("Upload new SCAP content file") %>

<%= render :partial => 'form' %>

app/views/scap_contents/welcome.html.erb
<% content_for(:title, _("SCAP Content")) %>
<div class="blank-slate-pf">
  <div class="blank-slate-pf-icon">
    <%= icon_text("key", "", :kind => "fa") %>
  </div>
  <h1><%= _('SCAP Content') %></h1>
  <p><%= _('The Security Content Automation Protocol (SCAP), combines a number of open standards that are used to enumerate software flaws and
        configuration issues related to security. ') %></br>
    <%= (_('In Foreman, scap_contents represent the SCAP security guides on your hosts, and create SCAP profiles for you to assign to hosts / host groups
    via %s') % link_to('compliance policies', policies_path)).html_safe %>
  </p>

  <div class="blank-slate-pf-main-action">
    <%= new_link(_('New SCAP Content'), {}, { :class => "btn-lg" }) %>
  </div>
</div>