config/routes.rb
Rails.application.routes.draw do
  match '/experimental/compliance' => 'react#index', :via => [:get]
  match '/experimental/compliance/*page' => 'react#index', :via => [:get]

  scope '/compliance' do
    resources :arf_reports, :only => %i[index show destroy] do
      member do
        get 'show_html'
        get 'parse_html'
        get 'parse_bzip'
        get 'download_html'
        get 'show_log'
      end
      collection do
        get 'auto_complete_search'
        get 'delete_multiple'
        post 'submit_delete_multiple'
      end
    end

    get 'dashboard', :to => 'compliance_dashboard#index', :as => "compliance_dashboard"

    resources :policies, :only => %i[index new show create edit update destroy] do
      member do
        get 'parse', :to => 'policies#parse'
        get 'dashboard', :to => 'policy_dashboard#index', :as => 'policy_dashboard'
      end
      collection do
        get 'auto_complete_search'
        post 'scap_content_selected'
        post 'tailoring_file_selected'
        post 'select_multiple_hosts'
        post 'update_multiple_hosts'
        post 'disassociate_multiple_hosts'
        post 'remove_policy_from_multiple_hosts'
      end
    end

    resources :scap_contents do
      collection do
        get 'auto_complete_search'
      end
    end

    resources :tailoring_files, :except => [:show] do
      member do
        get 'xml'
      end
      collection do
        get 'auto_complete_search'
      end
    end

    resources :openscap_proxies, :only => [] do
      member do
        get 'openscap_spool'
      end
    end

    resources :hosts, :only => [:show], :as => :compliance_hosts, :controller => :compliance_hosts
  end

  namespace :api, :defaults => { :format => 'json' } do
    scope "(:apiv)", :module => :v2, :defaults => { :apiv => 'v2' },
                     :apiv => /v2/, :constraints => ApiConstraints.new(:version => 2, :default => true) do
      namespace :compliance do
        resources :scap_contents, :except => %i[new edit] do
          member do
            get 'xml'
          end
          collection do
            post 'bulk_upload'
          end
        end
        resources :scap_content_profiles, :only => %i[index]

        resources :tailoring_files, :except => %i[new edit] do
          member do
            get 'xml'
          end
        end
        resources :policies, :except => %i[new edit] do
          member do
            get 'content'
            get 'tailoring'
          end
        end
        resources :arf_reports, :only => %i[index show destroy] do
          member do
            get 'download'
            get 'download_html'
          end
        end

        post 'arf_reports/:cname/:policy_id/:date', \
             :constraints => { :cname => /[^\/]+/ }, :to => 'arf_reports#create'
      end

      constraints(:id => /[^\/]+/) do
        resources :hosts, :only => [] do
          member do
            get :policies_enc
          end
        end
      end
    end
  end
end

Foreman::Application.routes.draw do
  resources :hosts do
    collection do
      post 'openscap_proxy_changed'
      post 'select_multiple_openscap_proxy'
      post 'update_multiple_openscap_proxy'
    end
  end

  resources :hostgroups do
    collection do
      post 'openscap_proxy_changed'
    end
  end
end

app/models/foreman_openscap/tailoring_file.rb
module ForemanOpenscap
  class TailoringFile < ApplicationRecord
    audited :except => [:scap_file]
    include Authorizable
    include Taxonomix
    include DataStreamContent
    include ScapFileContent

    has_many :policies
    has_many :scap_content_profiles, :dependent => :destroy
    validates :name, :presence => true, :uniqueness => true, :length => { :maximum => 255 }

    scoped_search :on => :name,              :complete_value => true
    scoped_search :on => :original_filename, :complete_value => true, :rename => :filename
    scoped_search :on => :created_at

    def fetch_profiles
      api = ProxyAPI::Openscap.new(:url => proxy_url)
      api.fetch_profiles_for_tailoring_file(scap_file)
    end
  end
end

app/controllers/api/v2/compliance/tailoring_files_controller.rb
module Api::V2
  module Compliance
    class TailoringFilesController < ::Api::V2::BaseController
      include Foreman::Controller::Parameters::TailoringFile
      include ForemanOpenscap::BodyLogExtensions
      include ForemanOpenscap::Api::V2::ScapApiControllerExtensions

      before_action :find_resource, :except => %w[index create]

      api :GET, '/compliance/tailoring_files', N_('List Tailoring files')
      param_group :search_and_pagination, ::Api::V2::BaseController
      add_scoped_search_description_for(::ForemanOpenscap::TailoringFile)

      def index
        @tailoring_files = resource_scope_for_index(:permission => :view_tailoring_files)
      end

      api :GET, '/compliance/tailoring_files/:id/xml', N_('Download a Tailoring file as XML')
      param :id, :identifier, :required => true

      def xml
        send_data @tailoring_file.scap_file,
                  :type     => 'application/xml',
                  :filename => @tailoring_file.original_filename || "#{@tailoring_file.name}.xml"
      end

      api :GET, '/compliance/tailoring_files/:id', N_('Show a Tailoring file')
      param :id, :identifier, :required => true
      def show
      end

      def_param_group :tailoring_file do
        param :tailoring_file, Hash, :required => true, :action_aware => true do
          param :name, String, :required => true, :desc => N_('Tailoring file name')
          param :scap_file, String, :required => true, :desc => N_('XML containing tailoring file')
          param :original_filename, String, :desc => N_('Original file name of the XML file')
          param_group :taxonomies, ::Api::V2::BaseController
        end
      end

      api :POST, '/compliance/tailoring_files', N_('Create a Tailoring file')
      param_group :tailoring_file, :as => :create

      def create
        @tailoring_file = ForemanOpenscap::TailoringFile.new(tailoring_file_params)
        process_response @tailoring_file.save
      end

      api :PUT, '/compliance/tailoring_files/:id', N_('Update a Tailoring file')
      param :id, :identifier, :required => true
      param_group :tailoring_file

      def update
        process_response @tailoring_file.update(tailoring_file_params)
      end

      api :DELETE, '/compliance/tailoring_files/:id', N_('Deletes a Tailoring file')
      param :id, :identifier, :required => true

      def destroy
        process_response @tailoring_file.destroy
      end

      private

      def find_resource
        not_found && return if params[:id].blank?
        instance_variable_set("@tailoring_file", resource_scope.find(params[:id]))
      end

      def action_permission
        case params[:action]
        when 'xml'
          :view
        else
          super
        end
      end
    end
  end
end

app/controllers/concerns/foreman/controller/parameters/tailoring_file.rb
module Foreman::Controller::Parameters::TailoringFile
  extend ActiveSupport::Concern

  class_methods do
    def tailoring_file_params_filter
      Foreman::ParameterFilter.new(::ForemanOpenscap::TailoringFile).tap do |filter|
        filter.permit :name, :scap_file, :original_filename, :location_ids => [], :organization_ids => []
      end
    end
  end

  def tailoring_file_params
    self.class.tailoring_file_params_filter.filter_params(params, parameter_filter_context)
  end
end

app/controllers/tailoring_files_controller.rb
class TailoringFilesController < ApplicationController
  include Foreman::Controller::AutoCompleteSearch
  include Foreman::Controller::Parameters::TailoringFile

  before_action :find_tailoring_file, :only => %i[destroy update edit xml]
  before_action :handle_file_upload, :only => %i[create update]

  def model_of_controller
    ::ForemanOpenscap::TailoringFile
  end

  def index
    @tailoring_files = resource_base_search_and_page.search_for(params[:search])
  end

  def new
    @tailoring_file = ::ForemanOpenscap::TailoringFile.new
  end

  def create
    @tailoring_file = ForemanOpenscap::TailoringFile.new(tailoring_file_params)
    if @tailoring_file.save
      process_success
    else
      process_error
    end
  rescue RestClient::Exception => e
    @tailoring_file.errors.add(:scap_file, :invalid, message: e.http_body)
    process_error
  end

  def edit
  end

  def update
    if @tailoring_file.update(tailoring_file_params)
      process_success
    else
      process_error
    end
  end

  def destroy
    if @tailoring_file.destroy
      process_success
    else
      process_error :object => @tailoring_file
    end
  end

  def xml
    send_data @tailoring_file.scap_file,
              :type     => 'application/xml',
              :filename => @tailoring_file.original_filename || "#{@tailoring_file.name}.xml"
  end

  private

  def find_tailoring_file
    @tailoring_file = resource_base.find(params[:id])
  end

  def handle_file_upload
    return unless params[:tailoring_file] && raw_file = params[:tailoring_file][:scap_file]
    params[:tailoring_file][:original_filename] = raw_file.original_filename
    params[:tailoring_file][:scap_file] = raw_file.tempfile.read if raw_file.respond_to?(:tempfile) && raw_file.tempfile.respond_to?(:read)
  end

  def action_permission
    case params[:action]
    when 'xml'
      :view
    else
      super
    end
  end
end

app/views/tailoring_files/_form.html.erb
<%= form_for @tailoring_file,
    :url => (@tailoring_file.id? ?
        tailoring_file_path(:id => @tailoring_file.id) : tailoring_files_path),
    :html => { :multipart => true } do |f| %>

  <%= base_errors_for @tailoring_file %>

  <ul class="nav nav-tabs" data-tabs="tabs">
    <li class="active"><a href="#primary" data-toggle="tab"><%= _("File Upload") %></a></li>
    <% if show_location_tab? %>
      <li><a href='#locations' data-toggle='tab'><%= _('Locations') %></a></li>
    <% end %>
    <% if show_organization_tab? %>
      <li><a href='#organizations' data-toggle='tab'><%= _('Organizations') %></a></li>
    <% end %>
  </ul>
  <div class="tab-content">
    <div class="tab-pane active" id="primary">
      <%= text_f(f, :name) %>
      <%= file_field_f f, :scap_file, :file_name => @tailoring_file.original_filename, :label_help => _("DataStream Tailoring file") %>
    </div>
    <%= render 'taxonomies/loc_org_tabs', :f => f, :obj => @tailoring_file %>
    <%= submit_or_cancel f %>
  </div>
<% end %>

app/views/tailoring_files/_list.html.erb
<table class="<%= table_css_classes('table-fixed') %>">
  <tr>
    <th class="col-md-4"><%= sort :name, as: _('Name') %></th>
    <th class="col-md-5"><%= sort :filename, as: _('File name') %></th>
    <th class="col-md-2"><%= sort :created_at, as: _('Created at') %></th>
    <th class="col-md-1"><%= _('Actions') %></th>
  </tr>
  <% @tailoring_files.each do |file| %>
    <tr>
      <td class="ellipsis">
        <%= link_to_if_authorized file.name, hash_for_edit_tailoring_file_path(:id => file.id) %>
      </td>
      <td>
        <%= file.original_filename %>
      </td>
      <td>
        <%= date_time_relative_value(file.created_at.getlocal) %>
      </td>
      <td>
        <%= action_buttons(
                display_delete_if_authorized(hash_for_tailoring_file_path(:id => file.id),
                                             :data => {:confirm => _("Delete tailoring file %s?") % file.name}),
                display_link_if_authorized(_("Download"), hash_for_xml_tailoring_file_path(:id => file.id), :data => { :no_turbolink => true })
            ) %>
      </td>
    </tr>
  <% end %>
</table>

<%= will_paginate_with_info @tailoring_files %>

app/views/tailoring_files/edit.html.erb
<% title _("Edit %s") % @tailoring_file.name %>
<%= breadcrumbs(:resource_url => api_compliance_tailoring_files_path,
                :name_field => 'name') %>

<%= render :partial => 'form' %>

app/views/tailoring_files/index.html.erb
<% title _("Tailoring Files") %>
<% title_actions(display_link_if_authorized(_("Upload New Tailoring file"), hash_for_new_tailoring_file_path, :class => 'btn btn-primary'),
                scap_doc_button('tailoring-xccdf-profiles_security-compliance')) %>
<%= render :partial => 'list' %>

app/views/tailoring_files/new.html.erb
<% title _("Upload new Tailoring File") %>

<%= render :partial => 'form' %>

app/views/tailoring_files/welcome.html.erb
<% content_for(:title, _("Tailoring Files")) %>
<div class="blank-slate-pf">
  <div class="blank-slate-pf-icon">
    <%= icon_text("key", "", :kind => "fa") %>
  </div>
  <h1><%= _('Tailoring Files') %></h1>
  <p><%= _('It may sometimes be required to adjust the security policy to your specific needs. ') %></br>
    <%= (_('In Foreman, tailoring_files represent the custom modifications to default XCCDF profiles and they can be applied to hosts
    via %s') % link_to('compliance policies', policies_path)).html_safe %>
  </p>
  <div class="blank-slate-pf-main-action">
    <%= new_link(_('New Tailoring File'), {}, { :class => "btn-lg" }) %>
  </div>
</div>