config/routes.rb
Rails.application.routes.draw do
  match '/experimental/compliance' => 'react#index', :via => [:get]
  match '/experimental/compliance/*page' => 'react#index', :via => [:get]

  scope '/compliance' do
    resources :arf_reports, :only => %i[index show destroy] do
      member do
        get 'show_html'
        get 'parse_html'
        get 'parse_bzip'
        get 'download_html'
        get 'show_log'
      end
      collection do
        get 'auto_complete_search'
        get 'delete_multiple'
        post 'submit_delete_multiple'
      end
    end

    get 'dashboard', :to => 'compliance_dashboard#index', :as => "compliance_dashboard"

    resources :policies, :only => %i[index new show create edit update destroy] do
      member do
        get 'parse', :to => 'policies#parse'
        get 'dashboard', :to => 'policy_dashboard#index', :as => 'policy_dashboard'
      end
      collection do
        get 'auto_complete_search'
        post 'scap_content_selected'
        post 'tailoring_file_selected'
        post 'select_multiple_hosts'
        post 'update_multiple_hosts'
        post 'disassociate_multiple_hosts'
        post 'remove_policy_from_multiple_hosts'
      end
    end

    resources :scap_contents do
      collection do
        get 'auto_complete_search'
      end
    end

    resources :tailoring_files, :except => [:show] do
      member do
        get 'xml'
      end
      collection do
        get 'auto_complete_search'
      end
    end

    resources :openscap_proxies, :only => [] do
      member do
        get 'openscap_spool'
      end
    end

    resources :hosts, :only => [:show], :as => :compliance_hosts, :controller => :compliance_hosts
  end

  namespace :api, :defaults => { :format => 'json' } do
    scope "(:apiv)", :module => :v2, :defaults => { :apiv => 'v2' },
                     :apiv => /v2/, :constraints => ApiConstraints.new(:version => 2, :default => true) do
      namespace :compliance do
        resources :scap_contents, :except => %i[new edit] do
          member do
            get 'xml'
          end
          collection do
            post 'bulk_upload'
          end
        end
        resources :scap_content_profiles, :only => %i[index]

        resources :tailoring_files, :except => %i[new edit] do
          member do
            get 'xml'
          end
        end
        resources :policies, :except => %i[new edit] do
          member do
            get 'content'
            get 'tailoring'
          end
        end
        resources :arf_reports, :only => %i[index show destroy] do
          member do
            get 'download'
            get 'download_html'
          end
        end

        post 'arf_reports/:cname/:policy_id/:date', \
             :constraints => { :cname => /[^\/]+/ }, :to => 'arf_reports#create'
      end

      constraints(:id => /[^\/]+/) do
        resources :hosts, :only => [] do
          member do
            get :policies_enc
          end
        end
      end
    end
  end
end

Foreman::Application.routes.draw do
  resources :hosts do
    collection do
      post 'openscap_proxy_changed'
      post 'select_multiple_openscap_proxy'
      post 'update_multiple_openscap_proxy'
    end
  end

  resources :hostgroups do
    collection do
      post 'openscap_proxy_changed'
    end
  end
end

app/controllers/api/v2/compliance/policies_controller.rb
module Api::V2
  module Compliance
    class PoliciesController < ::Api::V2::BaseController
      include Foreman::Controller::SmartProxyAuth
      include Foreman::Controller::Parameters::PolicyApi
      include ForemanOpenscap::Api::V2::ScapApiControllerExtensions

      add_smart_proxy_filters %i[content tailoring], :features => 'Openscap'

      before_action :find_resource, :except => %w[index create]

      skip_after_action :log_response_body, :only => [:content]

      def policy_url(policy = nil)
        api_compliance_policy_url(@policy)
      end

      api :GET, '/compliance/policies', N_('List Policies')
      param_group :search_and_pagination, ::Api::V2::BaseController
      add_scoped_search_description_for(::ForemanOpenscap::Policy)

      def index
        @policies = resource_scope_for_index(:permission => :view_policies)
      end

      api :GET, '/compliance/policies/:id', N_('Show a Policy')
      param :id, :identifier, :required => true

      def show
      end

      def_param_group :policy do
        param :policy, Hash, :required => true, :action_aware => true do
          param :name, String, :required => true, :desc => N_('Policy name')
          param :description, String, :desc => N_('Policy description')
          param :scap_content_id, Integer, :required => true, :desc => N_('Policy SCAP content ID')
          param :scap_content_profile_id, Integer, :required => true, :desc => N_('Policy SCAP content profile ID')
          param :period, String, :desc => N_('Policy schedule period (weekly, monthly, custom)')
          param :weekday, String, :desc => N_('Policy schedule weekday (only if period == "weekly")')
          param :day_of_month, Integer, :desc => N_('Policy schedule day of month (only if period == "monthly")')
          param :cron_line, String, :desc => N_('Policy schedule cron line (only if period == "custom")')
          param :hostgroup_ids, Array, :desc => N_('Apply policy to host groups')
          param :host_ids, Array, :desc => N_('Apply policy to hosts')
          param :tailoring_file_id, Integer, :desc => N_('Tailoring file ID')
          param :tailoring_file_profile_id, Integer, :desc => N_('Tailoring file profile ID')
          param :deploy_by, ForemanOpenscap::Policy.deploy_by_variants, :required => true, :desc => N_('How the policy should be deployed')
          param_group :taxonomies, ::Api::V2::BaseController
        end
      end

      api :POST, '/compliance/policies', N_('Create a Policy')
      param_group :policy, :as => :create

      def create
        @policy = ForemanOpenscap::Policy.new(policy_params)
        ForemanOpenscap::LookupKeyOverrider.new(@policy).override
        process_response(@policy.errors.none? && @policy.save)
      end

      api :PUT, '/compliance/policies/:id', N_('Update a Policy')
      param :id, :identifier, :required => true
      param_group :policy

      def update
        process_response(@policy.change_deploy_type(policy_params))
      end

      api :DELETE, '/compliance/policies/:id', N_('Delete a Policy')
      param :id, :identifier, :required => true

      def destroy
        process_response @policy.destroy
      end

      api :GET, '/compliance/policies/:id/content', N_("Show a policy's SCAP content")
      param :id, :identifier, :required => true

      def content
        @scap_content = @policy.scap_content
        send_data @scap_content.scap_file,
                  :type     => 'application/xml',
                  :filename => @scap_content.original_filename
      end

      api :GET, '/compliance/policies/:id/tailoring', N_("Show a policy's Tailoring file")
      param :id, :identifier, :required => true

      def tailoring
        @tailoring_file = @policy.tailoring_file
        if @tailoring_file
          send_data @tailoring_file.scap_file,
                    :type => 'application/xml',
                    :filename => @tailoring_file.original_filename
        else
          render(:json => { :error => { :message => _("No Tailoring file assigned for policy with id %s") % @policy.id } }, :status => 404)
        end
      end

      private

      def find_resource
        not_found && return if params[:id].blank?
        instance_variable_set("@policy", resource_scope.find(params[:id]))
      end

      def action_permission
        case params[:action]
        when 'content', 'tailoring'
          :view
        else
          super
        end
      end
    end
  end
end

app/controllers/api/v2/policies_controller.rb
module Api
  module V2
    class PoliciesController < ::Api::V2::BaseController
      before_filter :find_resource, :except => %w{index create}

      def resource_name
        'Scaptimony::Policy'
      end

      def get_resource
        instance_variable_get :"@policy" or raise 'no resource loaded'
      end

      def policy_url(policy = nil)
        api_policy_url(@policy)
      end

      resource_description do
        resource_id 'scaptimony_policies'
        api_version 'v2'
        api_base_url "/api/v2"
      end

      api :GET, '/policies', N_('List SCAP contents')
      param_group :search_and_pagination, ::Api::V2::BaseController

      def index
        @policies = resource_scope_for_index(:permission => :edit_compliance)
      end

      api :GET, '/policies/:id', N_('Show an SCAP content')
      param :id, :identifier, :required => true

      def show
      end

      def_param_group :policy do
        param :policy, Hash, :required => true, :action_aware => true do
          param :name, String, :required => true, :desc => N_('Policy name')
          param :description, String, :desc => N_('Policy description')
          param :scap_content_id, Integer, :required => true, :desc => N_('Policy scap content id')
          param :scap_content_profile_id, Integer, :required => true, :desc => N_('Policy scap content profile id')
          param :period, String, :required => true, :desc => N_('Policy schedule period')
          param :weekday, String, :required => true, :desc => N_('Policy schedule weekday')
          param :hostgroup_ids, Array, :desc => N_('Apply policy to hostgroups')
          param_group :taxonomies, ::Api::V2::BaseController
        end
      end

      api :POST, 'policies', N_('Create a policy')
      param_group :policy, :as => :create

      def create
        @policy = Scaptimony::Policy.new(params[:policy])
        process_response @policy.save
      end

      api :PUT, '/policies/:id', N_('Update a policy')
      param :id, :identifier, :required => true
      param_group :policy

      def update
        process_response @policy.update_attributes(params[:policy])
      end

      api :DELETE, '/policies/:id', N_('Deletes a policy')
      param :id, :identifier, :required => true

      def destroy
        process_response @policy.destroy
      end

      private
      def find_resource
        not_found and return if params[:id].blank?
        instance_variable_set("@policy", resource_scope.find(params[:id]))
      end
    end
  end
end

app/controllers/concerns/foreman/controller/parameters/policy.rb
module Foreman::Controller::Parameters::Policy
  extend ActiveSupport::Concern
  include Foreman::Controller::Parameters::PolicyApi

  class_methods do
    def policy_params_filter
      Foreman::ParameterFilter.new(::ForemanOpenscap::Policy).tap do |filter|
        filter.permit(%i[current_step wizard_initiated] + filter_params_list)
      end
    end
  end
end

app/helpers/policies_helper.rb
module PoliciesHelper
  def profiles_selection
    return @scap_content.scap_content_profiles if @scap_content.present?
    return @policy.scap_content.scap_content_profiles if @policy.scap_content.present?
    return []
  end

  def policy_profile_from_scap_content(policy)
    policy.scap_content_profile.nil? ? "Default" : policy.scap_content_profile.title
  end

  def deploy_by_radios(f, policy)
    ForemanOpenscap::ConfigNameService.new.configs.map do |tool|
      popover_block = tag.span(popover("", config_inline_help(tool.inline_help)), class: 'scap_policy_popover')

      label = label_tag('', :class => 'col-md-2 control-label', :for => "policy_deploy_by_#{tool.type}") do
        tool.type.to_s.capitalize.html_safe
      end

      radio = content_tag(:div, :class => "col-md-2") do
        f.radio_button(:deploy_by, tool.type, :disabled => !tool.available?, :checked => deploy_by_radio_checked(policy, tool))
      end

      content_tag(:div, :class => "clearfix") do
        content_tag(:div, :class => "form-group") do
          label.html_safe + popover_block.html_safe + radio.html_safe
        end
      end
    end.join('').html_safe
  end

  def config_inline_help(help_hash)
    link = if help_hash[:route_helper_method] && respond_to?(help_hash[:route_helper_method])
             link_to_if_authorized help_hash[:replace_text], public_send(help_hash[:route_helper_method])
           else
             help_hash[:replace_text]
           end
    text = help_hash[:text]
    text = text.split(help_hash[:replace_text], 2).join(link) if help_hash.key?(:replace_text)
    text.html_safe
  end

  def deploy_by_radio_checked(policy, tool)
    type = policy.deploy_by ? policy.deploy_by.to_sym : :manual
    tool.type == type
  end

  def effective_policy_profile(policy)
    policy.tailoring_file ? policy.tailoring_file_profile.title : policy_profile_from_scap_content(policy)
  end

  def scap_content_selector(form)
    scap_contents = ::ForemanOpenscap::ScapContent.authorized(:view_scap_contents).all
    if scap_contents.length > 1
      select_f form, :scap_content_id, scap_contents, :id, :title,
               { :include_blank => _("Choose existing SCAP Content") },
               { :label => _("SCAP Content"),
                 :required => true,
                 :onchange => 'scap_content_selected(this);',
                 :'data-url' => method_path('scap_content_selected') }
    else
      select_f form, :scap_content_id, scap_contents, :id, :title,
               { :label => _("SCAP Content"),
                 :required => true,
                 :onchange => 'scap_content_selected(this);',
                 :'data-url' => method_path('scap_content_selected') }
    end
  end

  def scap_content_profile_selector(form)
    if profiles_selection.length == 1
      select_f form, :scap_content_profile_id, profiles_selection, :id, :title,
               { :selected => @policy.scap_content_profile_id },
               { :label => _("XCCDF Profile"),
                 :disabled => profiles_selection.empty? ? true : false,
                 :help_inline => :indicator }
    else
      select_f form, :scap_content_profile_id, profiles_selection, :id, :title,
               { :selected => @policy.scap_content_profile_id,
                 :include_blank => _("Default XCCDF profile") },
               { :label => _("XCCDF Profile"),
                 :disabled => profiles_selection.empty? ? true : false,
                 :help_inline => :indicator }
    end
  end

  def tailoring_file_selector(form)
    select_f form, :tailoring_file_id, ForemanOpenscap::TailoringFile.all.authorized(:view_tailoring_files), :id, :name,
             { :include_blank => _('Choose Tailoring File') },
             { :label => _('Tailoring File'),
               :onchange => 'tailoring_file_selected(this)',
               :'data-url' => method_path('tailoring_file_selected') }
  end

  def tailoring_file_profile_selector(form, tailoring_file)
    if tailoring_file
      select_f form, :tailoring_file_profile_id, tailoring_file.scap_content_profiles, :id, :title,
               { :selected => @policy.tailoring_file_profile_id },
               { :label => _("XCCDF Profile in Tailoring File"),
                 :help_inline => _("This profile will be used to override the one from scap content") }
    else
      # to make sure tailoring profile id is nil when tailoring file is deselected
      form.hidden_field(:tailoring_file_profile_id, :value => nil)
    end
  end

  def submit_or_cancel_policy(form, overwrite = nil, args = {})
    args[:cancel_path] ||= send("#{controller_name}_path")
    content_tag(:div, :class => "clearfix") do
      content_tag(:div, :class => "form-actions") do
        text    = overwrite ? overwrite : _("Submit")
        options = { :class => "btn btn-primary" }
        previous = form.object.first_step? ? ' ' : previous_link(form)
        cancel_and_submit = content_tag(:div, :class => "pull-right") do
          link_to(_("Cancel"), args[:cancel_path], :class => "btn btn-default") + ' ' +
              form.submit(text, options)
        end
        (previous + cancel_and_submit).html_safe
      end
    end
  end

  def show_partial_wizard(step)
    @policy.current_step == step ? 'show-pane' : 'hide-pane'
  end

  def previous_link(form)
    previous = content_tag(:span, "", :class => 'glyphicon glyphicon-chevron-left')
    content_tag(:div, :class => 'pull-left') do
      link_to(previous.html_safe, '#', :class => 'btn btn-default', :onclick => "previous_step('#{@policy.previous_step}')")
    end
  end

  def days_of_week_hash
    Hash[*Date::DAYNAMES.map { |day| [day.downcase, day] }.flatten]
  end

  def translate_steps(policy)
    policy.steps.map { |step| _(step) }
  end
end

app/views/policies/_form.html.erb
<%= javascript 'foreman_openscap/policy_edit' %>
<%= javascript 'foreman_openscap/period_selector' %>
<%= form_for @policy,
    :url => (@policy.id? ? policy_path(:id => @policy.id) : policies_path) do |f| %>
  <%= base_errors_for @policy %>

  <ul class="nav nav-tabs" data-tabs="tabs">
    <li class="active"><a href="#deployment" data-toggle="tab"><%= _("Deployment Options") %></a></li>
    <li><a href="#primary" data-toggle="tab"><%= _("General") %></a></li>
    <li><a href="#scap_content" data-toggle="tab"><%= _("SCAP Content") %></a></li>
    <li><a href="#scap_schedule" data-toggle="tab"><%= _("Schedule") %></a></li>
    <% if show_location_tab? %>
      <li><a href='#locations' data-toggle='tab'><%= _('Locations') %></a></li>
    <% end %>
    <% if show_organization_tab? %>
      <li><a href='#organizations' data-toggle='tab'><%= _('Organizations') %></a></li>
    <% end %>
    <li><a href='#hostgroups' data-toggle='tab'><%= _('Host Groups') %></a></li>
  </ul>
  <div class="tab-content">
    <div class="tab-pane active" id="deployment">
      <%= deploy_by_radios f, @policy %>
    </div>
    <div class="tab-pane" id="primary">
      <%= text_f(f, :name) %>
      <%= textarea_f(f, :description, :rows => :auto ) %>
      <%= counter_f(f, :treshold) %>
    </div>
    <div class="tab-pane" id="scap_content">
      <%= scap_content_selector(f) %>
      <span id="scap_content_profile_select">
        <%= scap_content_profile_selector(f) %>
      </span>
      <span>
        <%= tailoring_file_selector(f) %>
      </span>
      <span id="tailoring_file_profile_select">
        <% if @policy.tailoring_file %>
          <%= render 'tailoring_file_selected', :f => f, :policy => @policy, :tailoring_file => @policy.tailoring_file  %>
        <% end %>
      </span>

    </div>
    <div class="tab-pane" id="scap_schedule">
      <%= select_f(f, :period, %w[Weekly Monthly Custom], :downcase, :to_s,
                   { :include_blank => _('Choose period') },
                   { :onchange => 'period_selected(this)' }) %>
      <%= select_f(f, :weekday, days_of_week_hash, :first, :last, :include_blank => _('Choose weekday')) %>
      <%= select_f(f, :day_of_month, (1..31).to_a, :to_i, :to_s, :help_inline => _('Number of a day in month, note that not all months have same count of days')) %>
      <%= text_f(f, :cron_line, :help_inline => _('You can specify custom cron line, e.g. "0  3  *  *  *", separate each of 5 values by space')) %>
    </div>

    <%= render 'taxonomies/loc_org_tabs', :f => f, :obj => @policy %>
    <div class="tab-pane" id="hostgroups">
      <%= multiple_selects f, :hostgroups, Hostgroup,
                           @policy.hostgroup_ids,
                           {:disabled => @policy.used_hostgroup_ids } %>
    </div>
    <%= submit_or_cancel f %>
  </div>
<% end %>

app/views/policies/_list.html.erb
<table class="<%= table_css_classes('table-fixed') %>">
  <tr>
    <th><%= sort :name, as: _('Name') %></th>
    <th><%= sort :content, as: _('Content') %></th>
    <th><%= sort :profile, as: _('Profile') %></th>
    <th><%= sort :tailoring_file, :as => _('Tailoring File') %></th>
    <th><%= sort :tailoring_file_profile, :as => _('Effective Profile') %></th>
    <th><%= _('Actions') %></th>
  </tr>
  <% for policy in @policies %>
    <tr>
      <td class="ellipsis">
        <%= link_to_if_authorized(policy.name.to_s, hash_for_edit_policy_path(:id => policy.id)) %>
      </td>
      <td>
        <% if !policy.scap_content.nil? %>
          <%= link_to_if_authorized policy.scap_content.title,
                                         hash_for_edit_scap_content_path(:id => policy.scap_content) %>
        <% end %>
      </td>
      <td>
        <%= policy_profile_from_scap_content policy %>
      </td>
      <td>
        <% if policy.tailoring_file %>
          <%=  link_to_if_authorized policy.tailoring_file.name, hash_for_edit_tailoring_file_path(:id => policy.tailoring_file_id) %>
        <% else %>
          <%= _('None') %>
        <% end%>
      </td>
      <td>
        <%= effective_policy_profile policy %>
      </td>
      <td>
        <%= action_buttons(
                display_link_if_authorized(_("Dashboard"), hash_for_policy_dashboard_policy_path(:id => policy.id)),
                display_link_if_authorized(_("Show Guide"), hash_for_policy_path(:id => policy.id)),
                display_delete_if_authorized(hash_for_policy_path(:id => policy.id),
                                             :data => {:confirm => _("Delete compliance policy %s with all of its reports?") % policy.name})
            ) %>
      </td>
    </tr>
  <% end %>
</table>

<%= will_paginate_with_info @policies %>

app/views/policies/_scap_content_results.html.erb
<%= fields_for @policy do |f| %>
  <%= scap_content_profile_selector(f) %>
<% end %>

app/views/policies/_tailoring_file_selected.html.erb
<%= fields_for policy do |f| %>
    <%= tailoring_file_profile_selector(f, tailoring_file) %>
<% end %>

app/views/policies/create.html.erb
<% title _("New Compliance Policy") %>
<%= render :partial => "policies/steps/step_form" %>

app/views/policies/disassociate_multiple_hosts.html.erb
<%= render 'hosts/selected_hosts', :hosts => @hosts %>
<%= form_for :policy,
             :url => remove_policy_from_multiple_hosts_policies_path(:host_ids => params[:host_ids]) do |f| %>
    <%= selectable_f f, :id, [[_('Select Compliance Policy'), 'disabled'],
                             ] + ForemanOpenscap::Policy.all.map{|e| [e.name, e.id]},{},
                        :onchange => 'tfm.hosts.table.toggleMultipleOkButton(this)' %>
<% end %>

app/views/policies/edit.html.erb
<% title _("Edit %s") % @policy.name %>
<%= breadcrumbs(:resource_url => api_compliance_policies_path,
                :name_field => 'name') %>

<%= render :partial => "form" %>

app/views/policies/index.html.erb
<%= javascript 'foreman_openscap/policy_edit' %>
<% title _("Compliance Policies") %>

<% title_actions(
  display_link_if_authorized(_("New Compliance Policy"), hash_for_new_policy_path, :class => "btn btn-primary"),
    scap_doc_button('Managing_Compliance_Policies_security-compliance')
  ) %>

<%= render :partial => 'list' %>

app/views/policies/new.html.erb
<% title _("New Compliance Policy") %>
<%= render :partial => "policies/steps/step_form" %>

app/views/policies/select_multiple_hosts.html.erb
<%= render 'hosts/selected_hosts', :hosts => @hosts %>

<%= form_for :policy,
             :url => update_multiple_hosts_policies_path(:host_ids => params[:host_ids]) do |f| %>
    <%= selectable_f f, :id, [[_("Select Compliance Policy"), "disabled"],
                             ] + ForemanOpenscap::Policy.all.map{|e| [e.name, e.id]},{},
                        :onchange => "tfm.hosts.table.toggleMultipleOkButton(this)" %>
<% end %>

app/views/policies/show.html.erb
<% title _("Details for Compliance Policy %s") % @policy.name %>
<%= breadcrumbs(:resource_url => api_compliance_policies_path,
                  :name_field => 'name') %>

<div class="row">
  <iframe style="min-height: 800px" height="100%" width="100%" frameborder="0" src="<%= parse_policy_path(@policy) %>"></iframe>
</div>

app/views/policies/welcome.html.erb
<% content_for(:title, _("Compliance Policies")) %>
<div class="blank-slate-pf">
  <div class="blank-slate-pf-icon">
    <%= icon_text("key", "", :kind => "fa") %>
  </div>
  <h1><%= _('Compliance Policies') %></h1>
  <p><%= (_('In Foreman, a compliance policy checklist is defined via %s.') % link_to(_('SCAP content'), scap_contents_path)).html_safe %></br>
    <%= _('Once SCAP content is present, you can create a policy, assign select host groups and schedule to run.') %>
  </p>

  <div class="blank-slate-pf-main-action">
    <%= new_link(_('New Policy'), {}, { :class => "btn-lg" }) %>
  </div>
</div>